### ISSUE TITLE
Keyboard Support

### ISSUE THREAD

**Issue by woooferz** [billyinferno/wxrdle#1]
It seems like only the letter buttons work on the demo, I'd love to self-host it. But I want the keyboard to work, please add this feature or tell me how to enable it.

**Comment by billyinferno** [comment]
What do you mean by only the letter buttons is work on the demo? You mean to use native keyboard instead?

**Comment by evacfk** [comment]
Woooferz seems to be correct, on the example page I can't type words with my keyboard. I have to manually press the letters that show up below. Pretty big pain point, otherwise fantastic project.

**Comment by onedr0p** [comment]
I think the point is to not use your phones keyboard and use the one built into the app.

**Comment by billyinferno** [comment]
@onedr0p Correct, as I need to manipulate which character is already being pressed and guessed wrong one, it will be very hard to use native keyboard for this.

**Comment by evacfk** [comment]
Would it be possible to enable this for Desktop? I generally play on my PC and screenshare for friends to play together. But there's 0 chance i'll sit here and click each letter I want to try versus using a keyboard like standard wordle. Letting us play incorrect letters would be fine as well. @billyinferno
