### ISSUE TITLE
Color confusion

### ISSUE THREAD

**Issue by ovizii** [billyinferno/wxrdle#2]
Hi there,

looks nice except when a letter is marked "grey" it seems to mean that it is not contained and yet on the keyboard below that same "not contained" letter is shown in a darker grey, this is confusing. 
Sorry if I haven't managed to express the problem clearly, maybe a screenshot will help.

The colors from the top should correspond to the colors at the bottom:
![image](https://user-images.githubusercontent.com/837902/162469245-93490b7d-375b-4454-9838-31d9891cb648.png)

**Comment by billyinferno** [comment]
Change the color so the wrong guess already the same, you can pull the latest docker, or rebuild from source code.

**Comment by ovizii** [comment]
thanks, I did a docker-compose pull and the colors are right now.
