### ISSUE TITLE
Is the word check working?

### ISSUE THREAD

**Issue by ovizii** [billyinferno/wxrdle#3]
I just tried your demo here: https://billyinferno.github.io/wxrdle/#/ and entered a random word: sioup - wxrdle has no issue with this word while Word Check is enabled and yourdictionary.com clearly shows this word does not exist, could you check what happened please?

![image](https://user-images.githubusercontent.com/837902/162471794-15666068-cb83-4f5a-967d-87027b1f6899.png)

![image](https://user-images.githubusercontent.com/837902/162471854-1d61abf6-1687-44c6-984a-290f6ae82973.png)

**Comment by billyinferno** [comment]
Thank you, seems that word.tips when you input sioup it will return with other possible word such as pious, I already fix the checking so it will iterate the result to check whether the search word is actually exists or not from the word.tips result.
You can pull the latest docker, or build from the source.

**Comment by ovizii** [comment]
thanks, I can confirm the issue is fixed. Let me add a related question: 

are you using an API to access word.tips and yourdictionary.com? Will they block me after a number of requests?

I just want to know if I will run into query limits if I host wxrdle for friends and family?
