### ISSUE TITLE
question about yourdictionary

### ISSUE THREAD

**Issue by ovizii** [billyinferno/wxrdle#7]
I entered orion, wxrdle claims the word does not exist, yourdictionary claims otherwise. What is going on here? Btw. I am a non-native English speaker, I'm just trying to figure out what is happening here :-)

https://www.yourdictionary.com/orion 

![image](https://user-images.githubusercontent.com/837902/162764470-fbc4b5f5-5c37-4797-99b3-b0a4e877bb5b.png)

**Comment by billyinferno** [comment]
I am using https://word.tips for the dictionary, yourdictionary is only used for searching the definition of the word (because word.tips definition is protected using CORS).

https://word.tips/unscramble/orion/
